# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI/CD
run-name: Running
on:
  push:
    branches: [ feat/cicd ]
  pull_request:
    branches: [ feat/cicd ]

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: trello-s3-bucket
  AWS_CODE_DEPLOY_APPLICATION: trello-CD
  AWS_CODE_DEPLOY_GROUP: trello-cd-group



permissions:
  contents: read

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: gradlew에 실행 권한 부여
      run: chmod +x ./gradlew

# # start.sh
#     - name: make start.sh
#       if: contains(github.ref, 'dev')
#       run: |
#         cd .
#         touch ./start.sh
#         echo "${{ secrets.START_SH }}" | base64 --decode > ./start.sh
#       shell: bash
      
    - name: 프로젝트 빌드
      run: ./gradlew clean build -x test
    - name: AWS credential 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
    - name: S3에 업로드
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/trello/$GITHUB_SHA.zip --source .
    - name: EC2에 배포
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=trello/$GITHUB_SHA.zip,bundleType=zip

      # uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      # with:
      #   arguments: build
